import 'dart:typed_data';

import 'package:coin/coin_chains.dart';
import 'package:test/test.dart';

void main() {
  setUpAll(() async {
    await VaultKeeper.initialize();
  });

  final ltc = LitecoinParams.litecoin.chain;
  final tltc = LitecoinParams.litecoinTestnet.chain;

  // Hex helpers for the vector assertions below.
  Uint8List h(String s) => Uint8List.fromList([
        for (var i = 0; i < s.length; i += 2)
          int.parse(s.substring(i, i + 2), radix: 16),
      ]);
  String hx(Uint8List b) =>
      b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

  group('MwebAddr real vectors', () {
    // Checksum-valid MWEB address strings generated by this implementation's
    // own encoder from the listed scan||spend pubkeys, kept here as a
    // regression of the encode/decode round-trip and the scan/spend split. The
    // Litecoin Core MWEB address format they target:
    // decode as bech32 (NOT bech32m) per the leading witness-version-0 5-bit
    // group, then ConvertBits<5,8,false> the remainder to exactly 66 bytes =
    // scan pubkey (33, compressed) || spend pubkey (33, compressed). See
    // litecoin-project/litecoin src/mweb/mweb_address (StealthAddress encoding).
    // The address string is the ground truth; the scan/spend values are the
    // expected ConvertBits output.

    test('mainnet vector 1 decodes to scan||spend (66 bytes)', () {
      const addr =
          'ltcmweb1qqvc0wyuk2r39ed482htlt5zxcqfzkqps0eev3rlejnrem0n79z2jz'
          'q5lhlv79ffu4c3v4au9z3ewks8raaz9f8t04634akevlwfdgkmkkq2cvvue';
      const scan =
          '0330f7139650e25cb6a755d7f5d046c0122b00307e72c88ff994c79dbe7e289521';
      const spend =
          '029fbfd9e2a53cae22caf7851472eb40e3ef44549d6faea35edb2cfb92d45b76b0';
      final d = MwebAddr.fromString(addr, ltc);
      expect(d.hrp, ltc.mwebHrp);
      expect(d.hrp, 'ltcmweb');
      expect(d.payload.length, 66);
      expect(hx(d.payload), scan + spend);
      // Scan/spend split check.
      expect(d.payload.sublist(0, 33), equals(h(scan)));
      expect(d.payload.sublist(33), equals(h(spend)));
    });

    test('mainnet vector 2 decodes to scan||spend (66 bytes)', () {
      const addr =
          'ltcmweb1qqfqfg0rnzlda6plm4memypplp33cj6lp0kr22j734y3mugnmkgpvq'
          'qe4g3tj8fhdrsm75kyy233u369pzhgrh6mz79g44w38jdq3nwsfhsss4xuj';
      const scan =
          '0240943c7317dbdd07fbaef3b2043f0c63896be17d86a54bd1a923be227bb202c0';
      const spend =
          '0335445723a6ed1c37ea58845463c8e8a115d03beb62f1515aba27934119ba09bc';
      final d = MwebAddr.fromString(addr, ltc);
      expect(d.hrp, ltc.mwebHrp);
      expect(d.payload.length, 66);
      expect(hx(d.payload), scan + spend);
      expect(d.payload.sublist(0, 33), equals(h(scan)));
      expect(d.payload.sublist(33), equals(h(spend)));
    });

    test('testnet vector decodes to scan||spend (66 bytes)', () {
      const addr =
          'tmweb1qqf5egdv93q8f7z5vp2c6j2ctpkapkm5r8rzhl29rhfyf3xwdxa5yc'
          'qm6pz53s4anx9lefas5r0e0zgl9280ktyyjn5e0c7ehgqeq2xml4v7mxkcy';
      const scan =
          '0269943585880e9f0a8c0ab1a92b0b0dba1b6e8338c57fa8a3ba489899cd37684c';
      const spend =
          '037a08a91857b3317f94f6141bf2f123e551df6590929d32fc7b374032051b7fab';
      final d = MwebAddr.fromString(addr, tltc);
      expect(d.hrp, tltc.mwebHrp);
      expect(d.hrp, 'tmweb');
      expect(d.payload.length, 66);
      expect(hx(d.payload), scan + spend);
      expect(d.payload.sublist(0, 33), equals(h(scan)));
      expect(d.payload.sublist(33), equals(h(spend)));
    });

    test('mainnet address rejected when parsed against testnet chain', () {
      const addr =
          'ltcmweb1qqvc0wyuk2r39ed482htlt5zxcqfzkqps0eev3rlejnrem0n79z2jz'
          'q5lhlv79ffu4c3v4au9z3ewks8raaz9f8t04634akevlwfdgkmkkq2cvvue';
      expect(() => MwebAddr.fromString(addr, tltc), throwsFormatException);
    });
  });

  group('MwebAddr', () {
    final synthetic = Uint8List.fromList(
      List<int>.generate(66, (i) => (i * 7 + 3) & 0xff),
    );

    test('synthetic round-trip encodes then decodes to same payload (mainnet)', () {
      final addr = MwebAddr(hrp: 'ltcmweb', payload: synthetic);
      final encoded = addr.encode(ltc);
      expect(encoded.startsWith('ltcmweb1'), isTrue);

      final decoded = MwebAddr.fromString(encoded, ltc);
      expect(decoded.hrp, 'ltcmweb');
      expect(decoded.payload, equals(synthetic));
      expect(decoded.payload.length, 66);
    });

    test('synthetic round-trip on testnet HRP tmweb', () {
      final addr = MwebAddr(hrp: 'tmweb', payload: synthetic);
      final encoded = addr.encode(tltc);
      expect(encoded.startsWith('tmweb1'), isTrue);

      final decoded = MwebAddr.fromString(encoded, tltc);
      expect(decoded.hrp, 'tmweb');
      expect(decoded.payload, equals(synthetic));
    });

    test('HRP mismatch throws (mainnet address parsed against testnet)', () {
      final encoded = MwebAddr(hrp: 'ltcmweb', payload: synthetic).encode(ltc);
      expect(() => MwebAddr.fromString(encoded, tltc), throwsFormatException);
    });

    test('mixed case throws', () {
      final encoded = MwebAddr(hrp: 'ltcmweb', payload: synthetic).encode(ltc);
      // Flip one character's case to create a mixed-case string.
      final mixed = encoded.substring(0, encoded.length - 1) +
          encoded[encoded.length - 1].toUpperCase();
      expect(() => MwebAddr.fromString(mixed, ltc), throwsFormatException);
    });

    test('bad checksum throws', () {
      final encoded = MwebAddr(hrp: 'ltcmweb', payload: synthetic).encode(ltc);
      // Corrupt the last data character.
      final last = encoded[encoded.length - 1];
      final replacement = last == 'q' ? 'p' : 'q';
      final corrupted =
          encoded.substring(0, encoded.length - 1) + replacement;
      expect(() => MwebAddr.fromString(corrupted, ltc), throwsFormatException);
    });
  });
}
